blog/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$',views.post_list,name='post_list'),
    url(r'^(?P<pk>\d+)/$',views.post_detail,name='post_detail'),
]

hellomeltingpod/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse

def hello(request):
    return HttpResponse('''
        <h1>Hello, <a href="http://facebook.com/askdjango/" target="_blank">AskDjango</a></h1>
    ''')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='blog')),
    url(r'^$' , hello),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models



class Post(models.Model):
    title = models.CharField(max_length=100)
    contrnt = models.TextField()
    photo = models.ImageField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

        

class Comment(models.Model):
    post = models.ForeignKey(Post)
    message = models.TextField()

blog/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from .models import Post

'''
def post_list(request):
    return render(request,'blog/post_list.html')
'''

post_list = ListView.as_view(model=Post)

post_detail = DetailView.as_view(model=Post)

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf8" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/journal/bootstrap.min.css" />
<style>
body {
    padding-top: 80px;
    padding-bottom: 80px;
}
</style>
</head>
<body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
                <a class="navbar-brand" href="#">멜팅팟 파이션</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                      <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                      </div>
                    </li>
                  </ul>
                  <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
              </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>{{ post.title }}</h1>

                <P><img src="{{ post.photo.url }}" /></P>

                {{ post.contrnt|linebreaks }}
                <hr />
                <a href="{% url "blog:post_list" %}" class="btn btn-primary">목록으로</a>
            </div>
        </div>
    </div>
   
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover table-bordered">
            {% for post in post_list %}
            <tr>
                <td>
                    <a href="{% url "blog:post_detail" post.pk %}">
                    {{ post.title }}
                </a>
                </td>
            </tr>
            {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}